channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/numba/label/dev/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/mro/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1=free
  - blas=1.0=mkl
  - certifi=2016.2.28=py36_0
  - dbus=1.10.20=0
  - expat=2.1.0=0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.50.2=1
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - icu=54.1=0
  - jbig=2.1=0
  - jpeg=9b=0
  - libffi=3.2.1=1
  - libgcc=5.2.0=0
  - libgfortran=3.0.0=1
  - libiconv=1.14=0
  - libpng=1.6.30=1
  - libtiff=4.0.6=3
  - libxcb=1.12=1
  - libxml2=2.9.4=0
  - mkl=2017.0.3=0
  - olefile=0.44=py36_0
  - openssl=1.0.2l=0
  - pcre=8.39=1
  - pip=9.0.1=py36_1
  - pyqt=5.6.0=py36_2
  - python=3.6.2=0
  - pytz=2017.2=py36_0
  - qt=5.6.2=5
  - readline=6.2=2
  - setuptools=36.4.0=py36_1
  - sip=4.18=py36_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py36_0
  - xz=5.2.3=0
  - zlib=1.2.11=0
  - pip:
    - altgraph==0.17.3
    - bottle==0.12.23
    - bottle-websocket==0.2.9
    - cycler==0.11.0
    - decorator==4.4.2
    - eel==0.14.0
    - future==0.18.2
    - gevent==22.10.1
    - gevent-websocket==0.10.1
    - greenlet==1.1.3.post0
    - imageio==2.15.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - networkx==2.5.1
    - numpy==1.15.0
    - opencv-python==4.5.5.64
    - pillow==8.4.0
    - protobuf==4.21.0
    - pydicom==2.3.0
    - pyinstaller==4.10
    - pyinstaller-hooks-contrib==2022.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.2.0
    - six==1.16.0
    - tensorboardx==2.5
    - threadpoolctl==3.1.0
    - tifffile==2020.9.3
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - whichcraft==0.6.1
    - zipp==3.6.0
    - zope-event==4.5.0
    - zope-interface==5.5.0


